trigger:
  -main

pool: fypagent

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    vsVersion: 'latest'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

steps:
  - script: echo testing
    displayName: Testing 1
  - script:
      echo this is the hostname
      echo $HOSTNAME
    displayName: Testing 2
    
stages:
- stages: Build
  displayname: Build Image
  jobsL
  - job: Build
    displayName: Build
    pool:
      vmImages: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: docker
        repository: pearlylin/fyp2023_team3
        
