trigger:
  -main

pool: fypagent

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    vsVersion: 'latest'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Whitesource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: '$(projectName)'

steps:
  - script: echo testing
    displayName: Testing 1
  - script:
      echo this is the hostname
      echo $HOSTNAME
    displayName: Testing 2