trigger:
  -main

pool: fypagent

variables:
  solution: 'C:\Users\21022677\Downloads\myagentfyp\_work\1\s\**\*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - script: echo testing
    displayName: Testing 1
    -script:
      echo this is the hostname
      echo $HOSTNAME
    displayName: Testing 2