trigger:
  -main

pool: fypagent

variables:
  solution: 'test'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - script: echo testing
    displayName: Testing 1
    -script:
      echo this is the hostname
      echo $HOSTNAME
    displayName: Testing 2